spring:
  application:
    name: cloud-order-service
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web

eureka:
  client:
    #表示向注册中心注册自己
    register-with-eureka: true
    #是否从EurekaServer中抓取已注册信息，默认为true，单节点配不配都可以，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    #EurekaServer服务器地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

  instance:
    instance-id: order80
    prefer-ip-address: true

server:
  port: 80

