spring:
  application:
    name: cloud-config-center
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          # git仓库地址
          uri: https://gitee.com/cymzn/springcloud-config.git
          search-paths:
            - springcloud-config
          username: #输入自己账号的用户名
          password: #输入自己账号的密码
          default-label: master #选择自己的分支，默认为main，我改成了master，以自己的为准
management:
  endpoints:
    web:
      exposure:
        include: 'busrefresh'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

server:
  port: 3344