spring:
  application:
    name: cloud-provider-payment
  zipkin:
      base-url: http://localhost:9411/
      sender:
        type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    # 配置数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    #配置连接数据库信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2002?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
eureka:
    client:
      #表示向注册中心注册自己
      register-with-eureka: true
      #是否从EurekaServer中抓取已注册信息，默认为true，单节点配不配都可以，集群必须设置为true才能配合ribbon使用负载均衡
      fetch-registry: true
      #EurekaServer服务器地址
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka
    instance:
      instance-id: payment8001
      #设置显示ip地址
      prefer-ip-address: true
server:
  port: 8001

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cym.springcloud.entities
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
