spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      #绑定器，设置绑定的消息中间件类型和信息
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            rabbitmq:
              host: localhost
              port: 5672
              username: guest
              password: guest
      #绑定的处理
      bindings:
        #设置通道的名字
        myChannel-in-0:
          #要使用的exchange定义
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
          group: cymA
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: receive-8002.com
    #设置显示ip地址
    prefer-ip-address: true
    #心跳间隔时间
    #服务器收到客户端最后一次心跳后等待的时间为5秒
    lease-expiration-duration-in-seconds: 5
    #心跳间隔时间
    lease-renewal-interval-in-seconds: 2
server:
  port: 8802