spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  sleuth:
      sampler:
        probability: 1
feign:
  client:
    config:
      default:
        #连接时间为1秒
        connectTimeout: 1000
        #读取超时时间为3秒
        read-timeout: 3000

logging:
  level:
    com.cym.springcloud.service.PaymentFeignService: debug





eureka:
  client:
    #表示向注册中心注册自己
    register-with-eureka: true
    #EurekaServer服务器地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

server:
  port: 80

