spring:
  application:
    name: cloud-order-service
feign:
  client:
    config:
      default:
        #连接时间为1秒
        connectTimeout: 1000
        #读取超时时间为3秒
        read-timeout: 3000
  #开启断路器
  circuitbreaker:
    enabled: true
hystrix:
  command:
    default: #也可以针对多个服务
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000 # 设置hystrix的超时时间为4000ms


logging:
  level:
    com.cym.springcloud.service.PaymentFeignService: debug

eureka:
  client:
    #表示向注册中心注册自己
    register-with-eureka: true
    #EurekaServer服务器地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
server:
  port: 80

